[package]
name = "touml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
rayon = "1.9.0"
rustpython-parser = {git = "https://github.com/RustPython/Parser.git"}
