[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/rdghosal/touml"
authors = ["Rahul D. Ghosal <rdghosal@proton.me>"]
license = "MIT"
